version: '3.8'

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:

services:
  postgres:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"
    networks:
      - app_network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5000:8080/tcp
    networks:
      - app_network
